spring:
  application:
    name: bebra-cinema

  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-main.xml
