spring:
  application:
    name: bebra-cinema

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cinema}
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-main.xml

logging:
  level:
    org:
      hibernate:
        type: trace